// The eight destinations. Everything that makes a world feel like *that* place -
// gravity, sky, palette, weather, what grows there - lives in one record, so a
// new planet is a data change rather than a code change.

export const PLANETS = [
  {
    mobs: { crawler: 0.8, warden: 0.2 },
    id: 'earth', name: 'Earth', subtitle: 'Home. Gravity you were built for.',
    gravity: 9.81, dayLength: 600, temperature: '+15 °C', distance: '1.00 AU', radius: '6 371 km',
    atmosphere: { breathable: true, label: 'N₂/O₂ at 101 kPa', suitDrain: 0 },
    orb: { base: '#2f6fd0', land: '#3f8f4a', cloud: '#ffffff', ring: null, glow: '#7fc9ff' },
    sky: {
      top: '#3a7bd5', horizon: '#a9d6f5', fog: '#b8d8f0', fogDensity: 0.0032,
      sun: '#fff6e0', sunIntensity: 1.15, sunSize: 24,
      ambientSky: '#8fc0ff', ambientGround: '#6b5a44', ambientIntensity: 0.55,
      stars: 0.0, companions: [],
    },
    terrain: {
      mode: 'terrestrial', base: 62, amplitude: 26, ridgeAmp: 34, roughness: 1,
      seaLevel: 58, sea: 'water', caves: 1, oreRich: 1,
      layers: { surface: 'grass', subsurface: 'dirt', deep: 'stone', beach: 'sand', underwater: 'gravel' },
      snowLine: 92, snowBlock: 'snow',
    },
    features: [
      { type: 'tree', density: 0.007, log: 'log', leaves: 'leaves', minH: 4, maxH: 7, on: ['grass'] },
      { type: 'boulder', density: 0.0012, block: 'cobble', on: ['grass', 'sand'] },
      { type: 'patch', density: 0.01, block: 'sand', radius: 3, on: ['grass'] },
    ],
    weather: { type: 'none' },
    hotbar: ['grass', 'dirt', 'stone', 'cobble', 'log', 'planks', 'sand', 'glass', 'lamp'],
    hazard: 'None. Enjoy the breathable air.',
    facts: ['Only world here with liquid surface water', 'One standard gravity: 9.81 m/s²', 'Jump height baseline'],
  },
  {
    mobs: { crawler: 0.55, warden: 0.45 },
    id: 'luna', name: 'The Moon', subtitle: 'One sixth of a g. Jump like a hero.',
    gravity: 1.62, dayLength: 1400, temperature: '-53 °C', distance: '384 400 km', radius: '1 737 km',
    atmosphere: { breathable: false, label: 'vacuum', suitDrain: 0.25 },
    orb: { base: '#9a9a97', land: '#6f6f6d', cloud: null, ring: null, glow: '#d8d8d0' },
    sky: {
      top: '#000205', horizon: '#0a0d18', fog: '#0a0d18', fogDensity: 0.0006,
      sun: '#ffffff', sunIntensity: 1.5, sunSize: 20,
      ambientSky: '#33405c', ambientGround: '#565654', ambientIntensity: 0.36,
      stars: 1.0,
      companions: [{ name: 'Earth', color: '#3a7bd5', accent: '#3f8f4a', size: 90, az: 2.1, el: 0.55 }],
    },
    terrain: {
      mode: 'terrestrial', base: 54, amplitude: 14, ridgeAmp: 22, roughness: 0.8,
      seaLevel: -1, sea: null, caves: 0.7, oreRich: 0.8, craters: 0.9,
      layers: { surface: 'moon_dust', subsurface: 'moon_dust', deep: 'moon_rock', beach: 'moon_dust', underwater: 'moon_rock' },
    },
    features: [
      { type: 'boulder', density: 0.002, block: 'moon_rock', on: ['moon_dust'] },
      { type: 'patch', density: 0.006, block: 'ice_ore', radius: 2, on: ['moon_dust'] },
    ],
    weather: { type: 'none' },
    hotbar: ['moon_dust', 'moon_rock', 'brick', 'hull', 'glass', 'lamp', 'solar', 'ice_ore', 'luminite'],
    hazard: 'No atmosphere. No sound. Long falls are slow, not safe.',
    facts: ['Gravity 1.62 m/s² - about 6× floatier', 'Regolith everywhere, water ice in shadow', 'Earth hangs still in the sky'],
  },
  {
    mobs: { crawler: 0.7, warden: 0.3 },
    id: 'mars', name: 'Mars', subtitle: 'Rust, canyons and a butterscotch sky.',
    gravity: 3.72, dayLength: 616, temperature: '-63 °C', distance: '1.52 AU', radius: '3 390 km',
    atmosphere: { breathable: false, label: 'CO₂ at 0.6 kPa', suitDrain: 0.2 },
    orb: { base: '#b4623a', land: '#8f4b2e', cloud: '#e8c9a0', ring: null, glow: '#ff9a5c' },
    sky: {
      top: '#7a4a33', horizon: '#d9a271', fog: '#c98a5e', fogDensity: 0.0042,
      sun: '#ffe2b8', sunIntensity: 0.95, sunSize: 16,
      ambientSky: '#d99a6e', ambientGround: '#7b4429', ambientIntensity: 0.58,
      stars: 0.25,
      companions: [{ name: 'Phobos', color: '#8b8178', accent: '#6a6058', size: 16, az: 0.7, el: 0.42 }],
    },
    terrain: {
      mode: 'terrestrial', base: 58, amplitude: 22, ridgeAmp: 46, roughness: 1.15,
      seaLevel: -1, sea: null, caves: 0.9, oreRich: 1.1, canyons: 0.8,
      layers: { surface: 'mars_sand', subsurface: 'mars_clay', deep: 'mars_rock', beach: 'mars_sand', underwater: 'mars_rock' },
      snowLine: 96, snowBlock: 'ice',
    },
    features: [
      { type: 'boulder', density: 0.002, block: 'mars_rock', on: ['mars_sand'] },
      { type: 'patch', density: 0.008, block: 'ice', radius: 3, on: ['mars_sand'] },
      { type: 'spire', density: 0.0018, block: 'mars_rock', minH: 5, maxH: 14, on: ['mars_sand', 'mars_rock'] },
    ],
    weather: { type: 'dust', color: '#d59a68', density: 0.5 },
    hotbar: ['mars_sand', 'mars_clay', 'mars_rock', 'ice', 'brick', 'hull', 'glass', 'lamp', 'solar'],
    hazard: 'Dust storms, 0.6% of Earth air pressure.',
    facts: ['Gravity 3.72 m/s² - jump 2.6× higher', 'Valles Marineris is 4 000 km long', 'A sol lasts 24 h 39 m'],
  },
  {
    mobs: { crawler: 0.8, warden: 0.2 },
    id: 'venus', name: 'Venus', subtitle: 'Furnace world under a lead-melting sky.',
    gravity: 8.87, dayLength: 1800, temperature: '+464 °C', distance: '0.72 AU', radius: '6 052 km',
    atmosphere: { breathable: false, label: 'CO₂ at 9 200 kPa, 464 °C', suitDrain: 0.6 },
    orb: { base: '#e0c246', land: '#c9a238', cloud: '#f5e3a8', ring: null, glow: '#ffe98a' },
    sky: {
      top: '#8a5f1e', horizon: '#e8b64e', fog: '#c98f2e', fogDensity: 0.019,
      sun: '#ffca6a', sunIntensity: 0.6, sunSize: 34,
      ambientSky: '#e0a83c', ambientGround: '#6b4416', ambientIntensity: 0.62,
      stars: 0.0, companions: [],
    },
    terrain: {
      mode: 'volcanic', base: 56, amplitude: 20, ridgeAmp: 40, roughness: 1.2,
      seaLevel: 48, sea: 'lava', caves: 1.1, oreRich: 1.2,
      layers: { surface: 'venus_crust', subsurface: 'basalt', deep: 'basalt', beach: 'sulfur', underwater: 'obsidian' },
    },
    features: [
      { type: 'boulder', density: 0.0022, block: 'obsidian', on: ['venus_crust'] },
      { type: 'spire', density: 0.0025, block: 'basalt', minH: 4, maxH: 12, on: ['venus_crust'] },
      { type: 'patch', density: 0.012, block: 'sulfur', radius: 3, on: ['venus_crust'] },
    ],
    weather: { type: 'ash', color: '#e8c98a', density: 0.35 },
    hotbar: ['venus_crust', 'basalt', 'obsidian', 'sulfur', 'lava', 'hull', 'glass', 'lamp', 'brick'],
    hazard: '92 bar of CO₂. Everything glows. Lava seas.',
    facts: ['Gravity 8.87 m/s² - nearly Earth-like', 'Surface hot enough to melt lead', 'A day is longer than its year'],
  },
  {
    mobs: { crawler: 0.3, warden: 0.7 },
    id: 'jupiter', name: 'Jupiter', subtitle: 'No ground. Build on the storm decks.',
    gravity: 24.79, dayLength: 240, temperature: '-108 °C', distance: '5.20 AU', radius: '69 911 km',
    cold: true,
    atmosphere: { breathable: false, label: 'H₂/He, crushing', suitDrain: 0.4 },
    orb: { base: '#d8a86a', land: '#a8713c', cloud: '#f0dcc0', ring: '#c9a98a', glow: '#ffd9a0', bands: true },
    sky: {
      top: '#a46c33', horizon: '#f2d49c', fog: '#d9a868', fogDensity: 0.0055,
      sun: '#fff0d0', sunIntensity: 0.55, sunSize: 8,
      ambientSky: '#e0b070', ambientGround: '#8a6a40', ambientIntensity: 0.6,
      stars: 0.35, companions: [{ name: 'Io', color: '#e0c246', accent: '#b48a2a', size: 22, az: 4.2, el: 0.3 }],
    },
    terrain: {
      mode: 'floating', base: 70, amplitude: 30, ridgeAmp: 0, roughness: 1,
      seaLevel: -1, sea: null, caves: 0, oreRich: 1.4,
      layers: { surface: 'cloud', subsurface: 'ammonia_ice', deep: 'storm_stone', beach: 'cloud', underwater: 'storm_stone' },
      deckLow: 40, deckHigh: 104,
    },
    features: [
      { type: 'crystal', density: 0.006, block: 'helium_ice', minH: 3, maxH: 7, on: ['cloud', 'ammonia_ice'] },
      { type: 'patch', density: 0.02, block: 'ammonia_ice', radius: 3, on: ['cloud'] },
    ],
    weather: { type: 'storm', color: '#f5e0b8', density: 0.6 },
    hotbar: ['cloud', 'ammonia_ice', 'storm_stone', 'helium_ice', 'hull', 'glass', 'lamp', 'luminite', 'brick'],
    hazard: 'Gravity 24.79 m/s². You can barely jump. Do not step off.',
    facts: ['2.5× Earth gravity - everything is heavy', 'No solid surface: only cloud decks', 'A day lasts under 10 hours'],
  },
  {
    mobs: { crawler: 0.6, warden: 0.4 },
    id: 'europa', name: 'Europa', subtitle: 'A cracked ice shell over a black ocean.',
    gravity: 1.31, dayLength: 850, temperature: '-160 °C', distance: '5.20 AU', radius: '1 561 km',
    cold: true,
    atmosphere: { breathable: false, label: 'trace O₂, hard radiation', suitDrain: 0.25 },
    orb: { base: '#dcecf5', land: '#b0784f', cloud: null, ring: null, glow: '#bfe9ff' },
    sky: {
      top: '#040914', horizon: '#12243a', fog: '#16283e', fogDensity: 0.0022,
      sun: '#ffffff', sunIntensity: 0.95, sunSize: 8,
      ambientSky: '#5a7ea8', ambientGround: '#63737f', ambientIntensity: 0.55,
      stars: 0.9,
      companions: [{ name: 'Jupiter', color: '#d8a86a', accent: '#a8713c', size: 200, az: 1.2, el: 0.38, bands: true }],
    },
    terrain: {
      mode: 'iceshell', base: 66, amplitude: 10, ridgeAmp: 16, roughness: 0.9,
      seaLevel: 52, sea: 'water', caves: 0.6, oreRich: 0.9,
      layers: { surface: 'europa_ice', subsurface: 'pack_ice', deep: 'basalt', beach: 'ice', underwater: 'pack_ice' },
      crustDepth: 12,
    },
    features: [
      { type: 'crystal', density: 0.005, block: 'crystal_block', minH: 3, maxH: 8, on: ['europa_ice', 'pack_ice'] },
      { type: 'patch', density: 0.01, block: 'ice', radius: 4, on: ['europa_ice'] },
      { type: 'boulder', density: 0.0016, block: 'pack_ice', on: ['europa_ice'] },
    ],
    weather: { type: 'snow', color: '#dff0ff', density: 0.4 },
    hotbar: ['europa_ice', 'pack_ice', 'ice', 'crystal_block', 'hull', 'glass', 'lamp', 'luminite', 'brick'],
    hazard: 'Jupiter’s radiation belt. The ocean below is 100 km deep.',
    facts: ['Gravity 1.31 m/s² - the floatiest world here', 'More liquid water than all of Earth', 'Jupiter fills a quarter of the sky'],
  },
  {
    mobs: { crawler: 0.75, warden: 0.25 },
    id: 'io', name: 'Io', subtitle: 'Four hundred volcanoes and nowhere to stand.',
    gravity: 1.80, dayLength: 450, temperature: '-143 °C', distance: '5.20 AU', radius: '1 821 km',
    atmosphere: { breathable: false, label: 'SO₂ frost, sulfur plumes', suitDrain: 0.5 },
    orb: { base: '#e0c246', land: '#a8541e', cloud: '#f5e08a', ring: null, glow: '#ffd24a' },
    sky: {
      top: '#1a1204', horizon: '#8a6a1e', fog: '#6a5218', fogDensity: 0.005,
      sun: '#fff0c0', sunIntensity: 0.7, sunSize: 8,
      ambientSky: '#c9a83c', ambientGround: '#6b4a12', ambientIntensity: 0.5,
      stars: 0.6,
      companions: [{ name: 'Jupiter', color: '#d8a86a', accent: '#a8713c', size: 260, az: 3.6, el: 0.3, bands: true }],
    },
    terrain: {
      mode: 'volcanic', base: 52, amplitude: 24, ridgeAmp: 44, roughness: 1.3,
      seaLevel: 44, sea: 'lava', caves: 1.2, oreRich: 1.3,
      layers: { surface: 'sulfur', subsurface: 'sulfur_crust', deep: 'basalt', beach: 'sulfur_crust', underwater: 'obsidian' },
    },
    features: [
      { type: 'spire', density: 0.004, block: 'basalt', minH: 6, maxH: 18, on: ['sulfur', 'sulfur_crust'] },
      { type: 'patch', density: 0.014, block: 'sulfur_crust', radius: 4, on: ['sulfur'] },
      { type: 'crystal', density: 0.006, block: 'luminite', minH: 2, maxH: 5, on: ['sulfur', 'sulfur_crust'] },
    ],
    weather: { type: 'ash', color: '#f0d878', density: 0.5 },
    hotbar: ['sulfur', 'sulfur_crust', 'basalt', 'obsidian', 'lava', 'luminite', 'hull', 'glass', 'lamp'],
    hazard: 'Sulfur plumes 400 km high. The ground is molten in places.',
    facts: ['Most volcanically active body known', 'Gravity 1.80 m/s²', 'Squeezed by Jupiter’s tides'],
  },
  {
    mobs: { crawler: 0.85, warden: 0.15 },
    id: 'titan', name: 'Titan', subtitle: 'Orange haze, methane lakes, and dunes.',
    gravity: 1.35, dayLength: 1600, temperature: '-179 °C', distance: '9.58 AU', radius: '2 575 km',
    cold: true,
    atmosphere: { breathable: false, label: 'N₂/CH₄ at 147 kPa, 90 K', suitDrain: 0.3 },
    orb: { base: '#c98a3a', land: '#8a5a2c', cloud: '#e8b06a', ring: null, glow: '#ffb45c' },
    sky: {
      top: '#7a4a12', horizon: '#e0a24a', fog: '#c07a2a', fogDensity: 0.013,
      sun: '#ffd9a0', sunIntensity: 0.42, sunSize: 12,
      ambientSky: '#d89a48', ambientGround: '#5a3a16', ambientIntensity: 0.6,
      stars: 0.0,
      companions: [{ name: 'Saturn', color: '#f0dcb4', accent: '#c9a86a', ringColor: '#e6d3a4', size: 300, az: 5.0, el: 0.34, ring: true }],
    },
    terrain: {
      mode: 'terrestrial', base: 56, amplitude: 16, ridgeAmp: 20, roughness: 0.85,
      seaLevel: 50, sea: 'methane', caves: 0.8, oreRich: 0.9, dunes: 1,
      layers: { surface: 'titan_sand', subsurface: 'titan_sand', deep: 'titan_rock', beach: 'titan_sand', underwater: 'titan_rock' },
    },
    features: [
      { type: 'tree', density: 0.005, log: 'alien_log', leaves: 'alien_leaves', minH: 5, maxH: 9, on: ['titan_sand', 'moss'] },
      { type: 'patch', density: 0.016, block: 'moss', radius: 4, on: ['titan_sand'] },
      { type: 'boulder', density: 0.0016, block: 'titan_rock', on: ['titan_sand'] },
    ],
    weather: { type: 'rain', color: '#c9b48a', density: 0.3 },
    hotbar: ['titan_sand', 'titan_rock', 'moss', 'alien_log', 'alien_leaves', 'methane', 'hull', 'glass', 'lamp'],
    hazard: 'Thicker air than Earth, 90 K cold. Methane drizzle.',
    facts: ['Only moon with a real atmosphere', 'Gravity 1.35 m/s²', 'Dunes of solid hydrocarbon sand'],
  },
];

export const PLANET_BY_ID = new Map(PLANETS.map((p) => [p.id, p]));
export const getPlanet = (id) => PLANET_BY_ID.get(id) ?? PLANETS[0];
