// Real Chromium smoke of the player-facing shell; isolated, ephemeral storage.
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
const url=process.env.LUNACRUST_TEST_URL || 'http://127.0.0.1:5178';
const out='output/ui'; await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL || 'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[], checks=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const check=(name,ok)=>{assert.ok(ok,name);checks.push(name);console.log('PASS',name)};
const settings=()=>page.evaluate(()=>window.__space.state.settings);
const setRange=async(id,value)=>page.locator(id).evaluate((n,v)=>{n.value=String(v);n.dispatchEvent(new Event('input',{bubbles:true}))},value);
try {
 await page.goto(url); await page.waitForFunction(()=>window.__space?.state.selected);
 await page.evaluate(()=>document.fonts.ready);
 check('eight keyboard-accessible planets',await page.locator('button.card').count()===8);
 await page.screenshot({path:`${out}/menu.png`});
 await page.locator('#btn-settings').click();
 await setRange('#set-fov',91);await setRange('#set-sens',1.7);await setRange('#set-rd',4);await setRange('#set-scale',1.25);
 await page.locator('#set-invert').check();await page.locator('#set-motion').check();
 await page.locator('#set-name').fill('Jan & crew');await page.locator('#set-name').blur();
 check('display settings apply immediately',await page.evaluate(()=>window.__space.game.camera.fov===91&&window.__space.game.settings.invertY===true));
 await page.locator('[data-settings-tab="audio"]').click();
 await setRange('#set-vol',0);await setRange('#set-music',.5);
 check('music independent of muted effects',await page.evaluate(()=>window.__space.music.volume===.5&&window.__space.audio.volume===0));
 await page.reload();await page.waitForFunction(()=>window.__space?.state.selected);
 const saved=await settings();check('all settings survive restart',saved.fov===91&&saved.sensitivity===1.7&&saved.renderDistance===4&&saved.invertY&&saved.reducedMotion&&saved.playerName==='Jan & crew'&&saved.volume===0&&saved.musicVolume===.5);
 await page.locator('#btn-settings').click();await page.screenshot({path:`${out}/settings.png`});
 await page.locator('#btn-reset-settings').click();check('restore defaults resets state and controls',(await settings()).fov===74&&(await settings()).playerName==='Explorer');
 await setRange('#set-rd',3);await setRange('#set-scale',1);
 await page.locator('#btn-resume').click();
 await page.locator('#btn-network').click();check('browser LAN explanation is visible',await page.locator('#network-platform-note').innerText().then(s=>s.includes('desktop')));
 await page.screenshot({path:`${out}/network-browser.png`});await page.locator('#btn-expedition').click();
 await page.setViewportSize({width:960,height:600});
 await page.locator('#btn-land').scrollIntoViewIfNeeded();check('launch reachable at minimum window',await page.locator('#btn-land').isVisible());
 await page.screenshot({path:`${out}/menu-960.png`});
 await page.locator('#btn-settings').click();await page.locator('#btn-reset-settings').scrollIntoViewIfNeeded();
 check('settings bottom reachable at minimum window',await page.locator('#btn-reset-settings').isVisible());
 await page.screenshot({path:`${out}/settings-960.png`});await page.locator('#btn-resume').click();
 await page.setViewportSize({width:1280,height:800});
 await page.locator('#seed-input').fill('777');
 await page.locator('#btn-land').click();
 await page.waitForFunction(()=>window.__space.game.spawned&&window.__space.game.running&&window.__space.state.screen==='play',{timeout:60000});
 await page.evaluate(()=>{window.__space.game.hooks.onPointerLost=()=>{};window.__space.game.setPaused(false);window.__space.show('play')});
 const start=await page.evaluate(()=>({...window.__space.game.player.pos}));
 await page.keyboard.down('w');await page.waitForTimeout(900);await page.keyboard.up('w');
 const end=await page.evaluate(()=>({...window.__space.game.player.pos}));
 check('actual movement input changes player position',Math.hypot(end.x-start.x,end.z-start.z)>.5);
 await page.keyboard.press('Digit4');check('hotbar selects from keyboard',await page.evaluate(()=>window.__space.game.slot===3));
 await page.keyboard.press('e');check('inventory opens from keyboard',await page.evaluate(()=>window.__space.screensOpen()));
 await page.screenshot({path:`${out}/inventory.png`});
 await page.keyboard.press('Escape');check('inventory closes',!(await page.evaluate(()=>window.__space.screensOpen())));
 await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__space.state.screen==='pause');check('pause opens',await page.evaluate(()=>window.__space.state.screen==='pause'));
 await page.locator('#btn-orbit').click();await page.waitForFunction(()=>window.__space.state.screen==='menu');
 check('save & return exposes continue',await page.locator('#btn-continue').isVisible());
 await page.locator('#btn-land').click();check('new expedition protects the saved world',await page.locator('#new-world-dialog').isVisible());
 await page.locator('#btn-cancel-new').click();check('cancel keeps the saved expedition',await page.locator('#btn-continue').isVisible());
 await page.locator('#btn-continue').click();await page.waitForFunction(()=>window.__space.game.spawned&&window.__space.state.screen==='play');
 check('continue preserves world seed',await page.evaluate(()=>window.__space.game.seed===777));
 await page.waitForTimeout(1200);await page.screenshot({path:`${out}/gameplay.png`});
 await writeFile(`${out}/state.json`,await page.evaluate(()=>window.render_game_to_text()));
 await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__space.state.screen==='pause');
 await page.locator('#btn-orbit').click();await page.waitForFunction(()=>window.__space.state.screen==='menu');
 await page.locator('#seed-input').fill('778');await page.locator('#btn-land').click();
 await page.screenshot({path:`${out}/replace-confirmation.png`});
 await page.locator('#btn-confirm-new').click();await page.waitForFunction(()=>window.__space.game.spawned&&window.__space.state.screen==='play');
 check('explicit confirmation starts the replacement world',await page.evaluate(()=>window.__space.game.seed===778));
 await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__space.state.screen==='pause');
 await page.locator('#btn-orbit').click();await page.waitForFunction(()=>window.__space.state.screen==='menu');
 check('confirmed new world persists',await page.evaluate(()=>JSON.parse(localStorage.getItem('spacemc:save:campaign-current')).worlds.earth.seed===778));
 check('no browser runtime or resource errors',errors.length===0);
} finally { await writeFile(`${out}/report.json`,JSON.stringify({checks,errors},null,2));await browser.close(); }
